name: Format with isort and Black

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  black:

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run isort
      uses: olance/isort-action@v1.1.0
      
    - name: Run Black
      uses: lgeiger/black-action@v1.0.1
      with:
        args: alma
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort / Black'
      
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
